
#name_of_the_excecutable: list of objects that will be needed 
#in the linking fase where all objects create this program
holamundo_created_with_make: holamundo.o 
	g++ holamundo.o -o holamundo_created_with_make
#under the excecutable[..] line goes the instruction that will create the excecutable 


#than go the diferent objects and how they will be created -------------------------

#the object holamundo.o is created with holamundo.c
holamundo.o: holamundo.c
	g++ -c holamundo.c
#and this is created with that instruction

#same with this one
#message.o: message.c message.h
#	g++ -c message.c

